spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: admin
    password: password
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o #gpt-3.5-turbo
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start_only
weather:
  api-key: ${WEATHER_API_KEY}
  api-url: http://api.weatherapi.com/v1
#  main:
#    banner-mode: off
#logging:
#  level:
#    root: off